/**
 * This is the AdminGUI it is pulled up only when an admin logs in. It is a 
 * JFrame with components that give the Admin their capabilities and access 
 * to everything they have permission to access
 */
package thehotspotsresort;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Your Name <Ben Fulker FGCU.EDU>
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form BookCancelLookUpGUI
     */
    public AdminGUI() {
        initComponents();                   //initiates the componentx
        
        cancelButton = false;
        adminCancelButton.setText("<html>Cancel or Edit<br /> Reservation</html>");
        revalidate();
        repaint();
        setLookAndFeel();                   //sets the look and feel
        this.setLocationRelativeTo(null);   //Centers the AdminGUI frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * This is GUI builder generated code sets the code based on programmers
     * guidance in the GUI Builder
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        adminCancelButton = new javax.swing.JButton();
        adminBookingButton = new javax.swing.JButton();
        adminLookUpButton = new javax.swing.JButton();
        printReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin GUI");
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 8));
        jPanel2.setAutoscrolls(true);
        jPanel2.setFocusCycleRoot(true);
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(330, 332));
        jPanel2.setMinimumSize(new java.awt.Dimension(330, 332));

        adminCancelButton.setBackground(new java.awt.Color(0, 153, 204));
        adminCancelButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        adminCancelButton.setText("Cancel or Edit Reservation");
        adminCancelButton.setToolTipText("This button enables the Admin to edit or cancel reservations by opening a selectable Jtable");
        adminCancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminCancelButton.setFocusable(false);
        adminCancelButton.setMaximumSize(new java.awt.Dimension(150, 150));
        adminCancelButton.setMinimumSize(new java.awt.Dimension(150, 150));
        adminCancelButton.setPreferredSize(new java.awt.Dimension(150, 150));
        adminCancelButton.setSelected(true);
        adminCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCancelButtonActionPerformed(evt);
            }
        });

        adminBookingButton.setBackground(new java.awt.Color(0, 153, 204));
        adminBookingButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        adminBookingButton.setText("Book A  Room");
        adminBookingButton.setToolTipText("This button is for booking a new reservation. When clicked it opens another GUI for selecting a room");
        adminBookingButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminBookingButton.setMaximumSize(new java.awt.Dimension(150, 150));
        adminBookingButton.setMinimumSize(new java.awt.Dimension(150, 150));
        adminBookingButton.setPreferredSize(new java.awt.Dimension(150, 150));
        adminBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBookingButtonActionPerformed(evt);
            }
        });

        adminLookUpButton.setBackground(new java.awt.Color(0, 153, 204));
        adminLookUpButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        adminLookUpButton.setText("Admin Look UP");
        adminLookUpButton.setToolTipText("This is the for the Admin to look up reservation.");
        adminLookUpButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminLookUpButton.setMaximumSize(new java.awt.Dimension(150, 150));
        adminLookUpButton.setMinimumSize(new java.awt.Dimension(150, 150));
        adminLookUpButton.setPreferredSize(new java.awt.Dimension(150, 150));
        adminLookUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLookUpButtonActionPerformed(evt);
            }
        });

        printReportButton.setBackground(new java.awt.Color(0, 153, 204));
        printReportButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        printReportButton.setText("Print Report");
        printReportButton.setToolTipText("This button is for looking up reservation information. It show all reservation data including payment information as only Admin has access ");
        printReportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printReportButton.setMaximumSize(new java.awt.Dimension(150, 150));
        printReportButton.setMinimumSize(new java.awt.Dimension(150, 150));
        printReportButton.setPreferredSize(new java.awt.Dimension(150, 150));
        printReportButton.setRequestFocusEnabled(false);
        printReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(adminCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(adminBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(adminLookUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(printReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminLookUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void adminBookingButtonActionPerformed(
		java.awt.event.ActionEvent evt
	) {//GEN-FIRST:event_adminBookingButtonActionPerformed
        if(evt.getSource() == adminBookingButton) {
            setVisible(false);  //makes current AdminGUI frame to invisible
            setEnabled(false);  //disables the AdminGUI frame
            revalidate();       //revalidates componenets
            repaint();          //rpaints the frame
            dispose();
            RoomGUI roomGui = new RoomGUI();
            roomGui.setAlwaysOnTop(true);
            roomGui.setAutoRequestFocus(true);
            roomGui.setFocusTraversalKeysEnabled(false);           
            roomGui.setVisible(true);
        }
    }//GEN-LAST:event_adminBookingButtonActionPerformed

    private void adminCancelButtonActionPerformed(
		java.awt.event.ActionEvent evt
	) {//GEN-FIRST:event_adminCancelButtonActionPerformed

        if(evt.getSource() == AdminGUI.adminCancelButton) {
            cancelButton = true;
            setVisible(false);  //makes current AdminGUI frame to invisible
            setEnabled(false);  //disables the AdminGUI frame
            revalidate();       //revalidates componenets
            repaint();          //rpaints the frame
            dispose();
            LookUpGUI adminEditLookUPGUI = new LookUpGUI();
            adminEditLookUPGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            adminEditLookUPGUI.setAlwaysOnTop(true);
            adminEditLookUPGUI.setAutoRequestFocus(true);
            adminEditLookUPGUI.setFocusTraversalKeysEnabled(false);           
            adminEditLookUPGUI.setVisible(true);
        }
    }//GEN-LAST:event_adminCancelButtonActionPerformed

    private void adminLookUpButtonActionPerformed(
		java.awt.event.ActionEvent evt
	) {//GEN-FIRST:event_adminLookUpButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == AdminGUI.adminLookUpButton) {
            setVisible(false);  //makes current AdminGUI frame to invisible
            setEnabled(false);  //disables the AdminGUI frame
            revalidate();       //revalidates componenets
            repaint();          //rpaints the frame
            dispose();
            LookUpGUI adminLookUPGUI = new LookUpGUI();
            adminLookUPGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            adminLookUPGUI.setAlwaysOnTop(true);
            adminLookUPGUI.setAutoRequestFocus(true);
            adminLookUPGUI.setFocusTraversalKeysEnabled(false);           
            adminLookUPGUI.setVisible(true);
            boolean check = false;
        }
      
    }//GEN-LAST:event_adminLookUpButtonActionPerformed

    private void printReportButtonActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_printReportButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == printReportButton) {
            setVisible(false);  //makes current AdminGUI frame to invisible
            setEnabled(false);  //disables the AdminGUI frame
            revalidate();       //revalidates componenets
            repaint();          //rpaints the frame
            dispose();
            PrintReportGUI report = new PrintReportGUI(); //instantiates print
            report.setAlwaysOnTop(true);
            report.setAutoRequestFocus(true);
            report.setFocusTraversalKeysEnabled(false);           
            report.setVisible(true);        //reportGUI and set visible to true
        }
    }//GEN-LAST:event_printReportButtonActionPerformed

    /**
     * Sets the look and feel of Frame based on OS on system that is running
     * the program
     * @param args the command line arguments
     */
    public static void setLookAndFeel() {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, 
		 * stay with the default look and feel.
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
		javax.swing.UIManager.getInstalledLookAndFeels())  {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(
				AdminGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(
				AdminGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(
				AdminGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(	
				AdminGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        }

  
    }
    
    ///////// Start of Variable and Attribute Declaration//////////////
    protected static boolean cancelButton;// = false;
    protected static boolean bookButton;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton adminBookingButton;
    protected static javax.swing.JButton adminCancelButton;
    protected static javax.swing.JButton adminLookUpButton;
    private javax.swing.JPanel jPanel2;
    protected static javax.swing.JButton printReportButton;
    // End of variables declaration//GEN-END:variables
}
