/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotspotsresort;

import org.jdesktop.swingx.JXMonthView;
/**
 *
 * @author Your Name <Ben Fulker FGCU.EDU>
 */
public class RoomGUI extends javax.swing.JFrame {

    /**
     * Creates new form RoomGUI
     */
    public RoomGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomThreeJButton = new javax.swing.JButton();
        roomTwoJButton = new javax.swing.JButton();
        roomOneJButton = new javax.swing.JButton();
        roomFourJButton = new javax.swing.JButton();
        roomFiveJButton = new javax.swing.JButton();
        roomSixJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roomThreeJButton.setText("3");
        roomThreeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomThreeJButtonActionPerformed(evt);
            }
        });

        roomTwoJButton.setText("2");
        roomTwoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTwoJButtonActionPerformed(evt);
            }
        });

        roomOneJButton.setText("1");
        roomOneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomOneJButtonActionPerformed(evt);
            }
        });

        roomFourJButton.setText("4");
        roomFourJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomFourJButtonActionPerformed(evt);
            }
        });

        roomFiveJButton.setText("5");
        roomFiveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomFiveJButtonActionPerformed(evt);
            }
        });

        roomSixJButton.setText("6");
        roomSixJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomSixJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomFourJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomFiveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomOneJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomTwoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomThreeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomSixJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomTwoJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(roomOneJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomThreeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomFourJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(roomFiveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomSixJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomOneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomOneJButtonActionPerformed
        // TODO add your handling code here:
        MyJXMonthViewCalendar roomOneCalendar = new MyJXMonthViewCalendar();
    }//GEN-LAST:event_roomOneJButtonActionPerformed

    private void roomTwoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTwoJButtonActionPerformed
        // TODO add your handling code here:
        MyJXMonthViewCalendar roomTwoCalendar = new MyJXMonthViewCalendar();
    }//GEN-LAST:event_roomTwoJButtonActionPerformed

    private void roomThreeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomThreeJButtonActionPerformed
        // TODO add your handling code here:
        MyJXMonthViewCalendar roomThreeCalendar = new MyJXMonthViewCalendar();
    }//GEN-LAST:event_roomThreeJButtonActionPerformed

    private void roomFourJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomFourJButtonActionPerformed
        // TODO add your handling code here:
        MyJXMonthViewCalendar roomFourCalendar = new MyJXMonthViewCalendar();
    }//GEN-LAST:event_roomFourJButtonActionPerformed

    private void roomFiveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomFiveJButtonActionPerformed
        // TODO add your handling code here:
        MyJXMonthViewCalendar roomFiveCalendar = new MyJXMonthViewCalendar();
    }//GEN-LAST:event_roomFiveJButtonActionPerformed

    private void roomSixJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomSixJButtonActionPerformed
        // TODO add your handling code here:
        MyJXMonthViewCalendar roomSixCalendar = new MyJXMonthViewCalendar();
    }//GEN-LAST:event_roomSixJButtonActionPerformed
                  

    /**
     * @param args the command line arguments
     */
    public static void setLookAndFeel() {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the
        default look and feel.For details see 
        http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                            javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException | InstantiationException | 
                                                        IllegalAccessException | 
                                 javax.swing.UnsupportedLookAndFeelException ex) 
        {
            java.util.logging.Logger.getLogger(RoomGUI.class.getName()).
                                  log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton roomFiveJButton;
    private javax.swing.JButton roomFourJButton;
    private javax.swing.JButton roomOneJButton;
    private javax.swing.JButton roomSixJButton;
    private javax.swing.JButton roomThreeJButton;
    private javax.swing.JButton roomTwoJButton;
    // End of variables declaration//GEN-END:variables
}
