/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotspotsresort;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Your Name <Ben Fulker FGCU.EDU>
 */
public class StaffGUI extends javax.swing.JFrame {

    /**
     * Creates new form BookCancelLookUpGUI
     */
    public StaffGUI() {
        initComponents();
        setLookAndFeel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffBookingButton = new javax.swing.JButton();
        staffCancelButton = new javax.swing.JButton();
        staffLookUpJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff GUI");

        staffBookingButton.setText("Book A Room");
        staffBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffBookingButtonActionPerformed(evt);
            }
        });

        staffCancelButton.setText("Cancel A Booking");
        staffCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffCancelButtonActionPerformed(evt);
            }
        });

        staffLookUpJButton.setText("Look Up Reservations");
        staffLookUpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLookUpJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(staffLookUpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(staffCancelButton)
                            .addComponent(staffBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(staffBookingButton)
                .addGap(18, 18, 18)
                .addComponent(staffCancelButton)
                .addGap(18, 18, 18)
                .addComponent(staffLookUpJButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffBookingButtonActionPerformed
       RoomGUI roomGUI = new RoomGUI();
       roomGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       roomGUI.setVisible(true);
    }//GEN-LAST:event_staffBookingButtonActionPerformed

    private void staffCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffCancelButtonActionPerformed
        // TODO add your handling code here:
      /*   try {
            TheHotSpotsResort.cancelButtonClick();
        } catch (IOException ex) {
            Logger.getLogger(BookCancelLookUpGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        cancelButton = true;*/
    }//GEN-LAST:event_staffCancelButtonActionPerformed

    private void staffLookUpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffLookUpJButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_staffLookUpJButtonActionPerformed

    /**
     *
     */
    public static void setLookAndFeel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    protected static boolean cancelButton = false;
    protected static boolean bookButton;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton staffBookingButton;
    protected static javax.swing.JButton staffCancelButton;
    private javax.swing.JButton staffLookUpJButton;
    // End of variables declaration//GEN-END:variables
}
