/**
 * This is the StaffGUI it is pulled up only when an staff logs in. It is a 
 * JFrame with components that give the Staff their capabilities and access 
 * to everything they have permission to access
 */
package thehotspotsresort;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Your Name <Ben Fulker FGCU.EDU>
 */
public class StaffGUI extends javax.swing.JFrame {

    /**
     * Creates new form BookCancelLookUpGUI
     */
    public StaffGUI() {
        initComponents();
        setLookAndFeel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        staffBookingButton = new javax.swing.JButton();
        staffCancelButton = new javax.swing.JButton();
        staffLookUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff GUI");
        setMaximumSize(new java.awt.Dimension(330, 332));
        setName("StaffFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(330, 332));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 10));
        jPanel2.setAutoscrolls(true);
        jPanel2.setFocusCycleRoot(true);
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(330, 332));
        jPanel2.setMinimumSize(new java.awt.Dimension(330, 332));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 15, 5));

        staffBookingButton.setBackground(new java.awt.Color(255, 0, 0));
        staffBookingButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        staffBookingButton.setText("Book A  Room");
        staffBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffBookingButtonActionPerformed(evt);
            }
        });
        jPanel2.add(staffBookingButton);

        staffCancelButton.setBackground(new java.awt.Color(255, 0, 0));
        staffCancelButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        staffCancelButton.setText("Cancel Reservation");
        staffCancelButton.setFocusable(false);
        staffCancelButton.setSelected(true);
        staffCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffCancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(staffCancelButton);

        staffLookUpButton.setBackground(new java.awt.Color(255, 0, 0));
        staffLookUpButton.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 24)); // NOI18N
        staffLookUpButton.setText("Admin Look UP");
        staffLookUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLookUpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(staffLookUpButton);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 332));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffBookingButtonActionPerformed(
		java.awt.event.ActionEvent evt
	) {//GEN-FIRST:event_adminBookingButtonActionPerformed
       RoomGUI roomGui = new RoomGUI();
       roomGui.setVisible(true);
    }//GEN-LAST:event_adminBookingButtonActionPerformed

    private void staffCancelButtonActionPerformed(
		java.awt.event.ActionEvent evt
	) {//GEN-FIRST:event_adminCancelButtonActionPerformed

        if(evt.getSource() == StaffGUI.staffCancelButton) {
            cancelButton = true;
            LookUpGUI adminEditLookUPGUI = new LookUpGUI();
            adminEditLookUPGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            adminEditLookUPGUI.setVisible(true);
        }
    }//GEN-LAST:event_adminCancelButtonActionPerformed

    private void staffLookUpButtonActionPerformed(
		java.awt.event.ActionEvent evt
	) {//GEN-FIRST:event_adminLookUpButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == StaffGUI.staffLookUpButton) {
            LookUpGUI adminLookUPGUI = new LookUpGUI();
            adminLookUPGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            adminLookUPGUI.setVisible(true);
                 boolean check = false;
        }
      
    }//GEN-LAST:event_adminLookUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void setLookAndFeel() {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, 
		 * stay with the default look and feel.
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
		javax.swing.UIManager.getInstalledLookAndFeels())  {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()
			).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    protected static boolean cancelButton = false;
    protected static boolean bookButton;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    protected static javax.swing.JButton staffBookingButton;
    protected static javax.swing.JButton staffCancelButton;
    protected static javax.swing.JButton staffLookUpButton;
    // End of variables declaration//GEN-END:variables
}
